version: "3.9"

services:
  kafka-1:
    image: apache/kafka:3.9.2-rc0
    ports: 
     - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_NODE_ID: 1
      KAFKA_CLUSTER_ID: "ghH5Qg314fTg43g5df"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://:9091,EXTERNAL://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9091,EXTERNAL://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_LEADER_REBALANCE_ENABLE: "true"
      KAFKA_LEADER_IMBALANCE_PER_BROKER_PERCENTAGE: "10"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_HEAP_OPTS: -Xmx1G -Xms1G
    volumes:
      - kafka1:/var/lib/kafka/data

  kafka-2:
    image: apache/kafka:3.9.2-rc0
    ports: 
     - "9082:9082"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_NODE_ID: 2
      KAFKA_CLUSTER_ID: "ghH5Qg314fTg43g5df"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://:9091,EXTERNAL://:9082,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9091,EXTERNAL://localhost:9082
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_LEADER_REBALANCE_ENABLE: "true"
      KAFKA_LEADER_IMBALANCE_PER_BROKER_PERCENTAGE: "10"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_HEAP_OPTS: -Xmx1G -Xms1G
    volumes:
      - kafka2:/var/lib/kafka/data

  kafka-3:
    image: apache/kafka:3.9.2-rc0
    ports: 
    - "9072:9072"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_NODE_ID: 3
      KAFKA_CLUSTER_ID: "ghH5Qg314fTg43g5df"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://:9091,EXTERNAL://:9072,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:9091,EXTERNAL://localhost:9072
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_LEADER_REBALANCE_ENABLE: "true"
      KAFKA_LEADER_IMBALANCE_PER_BROKER_PERCENTAGE: "10"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_HEAP_OPTS: -Xmx1G -Xms1G
    volumes:
      - kafka3:/var/lib/kafka/data

  kafka-init:
    image: apache/kafka:3.9.2-rc0
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    entrypoint: [ '/bin/sh', '-c']
    command: |
      "
      echo -e 'Initializing kafka cluster topics...'
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9091 --create --if-not-exists --topic drom.bulletin.posted --replication-factor 3 --partitions 3
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9091 --create --if-not-exists --topic drom.bulletin.pictures --replication-factor 3 --partitions 3
      echo -e 'Kafka topics in cluster are:'
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9091 --list
      "

  spark:
    build: pyspark-transforms/
    ports:
      - 7077:7077



  datalake-consumer:
    build: minio-datalake/
    # volumes:
    #   - /minio-datalake/kafka-consumer:/kafka-consumer


  MINIO-DATALAKE:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    ports:
    - 9000:9000
    - 9001:9001
    command: [ "server", "--console-address", ":9001", "/data" ]
    environment:
      MINIO_ROOT_USER: "dev_admin"
      MINIO_ROOT_PASSWORD: "dev_password"
    volumes:
      - minio-volume:/data

  minio-init:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    depends_on:
      - MINIO-DATALAKE
    restart: on-failure
    entrypoint: [ '/bin/sh', '-c']
    command: |
      "
      echo -e 'Initializng MinIO buckets...'
      sleep 10
      /usr/bin/mc alias set miniodatalake http://minio-datalake:9000 dev_admin dev_password
      /usr/bin/mc mb --ignore-existing miniodatalake/bulletin-pictures
      /usr/bin/mc mb --ignore-existing miniodatalake/bulletins
      echo -e 'MinIO buckets are:'
      /usr/bin/mc ls miniodatalake
      "

volumes:
  kafka1:
  kafka2:
  kafka3:
  minio-volume: